[pr_reviewer]
require_ticket_analysis_review = true  # Enable ticket compliance checking (default: true)
require_ticket_labels = true         # Add compliance labels (default: false)
require_no_ticket_labels = true   # Label PRs without tickets (default: false)

[github_app]

pr_commands = [
    "/describe",
    "/review",
    "/improve",
    "/compliance",
] 
handle_push_trigger = true
push_commands = [
    "/describe",
    "/review",
    "/improve",
    "/compliance",
]
