[github_app]
handle_push_trigger = true

pr_commands = [
    "/describe",
    "/improve",
    "/review"
] 

push_commands = [
    "/describe",
    "/improve",
    "/review"
]

[config]
enable_custom_labels=true

[custom_labels."Auto approved by Qodo Agent"]
description = "PR auto-approved if only Low risk problems exist"

