[github_app]
handle_push_trigger = true

pr_commands = [
    "/describe",
    "/improve",
    "/review"
] 

push_commands = [
    "/describe",
    "/improve",
    "/review"
]

[config]
enable_custom_labels=true
enable_comment_approval = true # For approval via comments
enable_auto_approval = true   # For criteria-based auto-approval
auto_approve_for_low_review_effort = 2m  #number between 1 and 5
auto_approve_for_no_suggestions = true

[custom_labels."Auto Approved - Code Suggestions"]
description = "PR auto-approved based on no suggestions"

[custom_labels."Auto Approved - LoE"]
description = "PR auto-approved based on low LOE"
