[github_app]
handle_push_trigger = true

pr_commands = [
    "/describe",
    "/improve",
    "/review"
] 

push_commands = [
    "/describe",
    "/improve",
    "/review"
]

[config]
enable_custom_labels=true

[custom_labels."Needs Human Review"]
description = "Needs Human Review"

[custom_labels."Auto-merged by Agent"]
description = "This PR was automatically merged by the merge2close agent"
