
[pr_code_suggestions]
focus_only_on_problems=false
suggestions_score_threshold=0

[github_app]
handle_push_trigger = true

pr_commands = [
    "/describe",
    "/improve --pr_code_suggestions.num_code_suggestions_per_chunk=6",
    "/review"
] 

push_commands = [
    "/describe",
    "/improve --pr_code_suggestions.num_code_suggestions_per_chunk=6",
    "/review"
]
