[github_app]
handle_push_trigger = true

pr_commands = [
    "/describe",
    "/improve",
    "/review"
] 

push_commands = [
    "/describe",
    "/improve",
    "/review"
]

[config]
enable_custom_labels=true

# For approval via comments
enable_comment_approval = true 

# For criteria-based auto-approval
enable_auto_approval = true   

# number between 1 and 5 where 1 is low
#auto_approve_for_low_review_effort = 2  

# auto-approve if there are no outstanding code suggestions
auto_approve_for_no_suggestions = true

# auto-approval for /review will not trigger here if no ticket is linked to the PR, 
# or if the PR is not fully compliant with a linked ticket.
#ensure_ticket_compliance = true 

